package com.bel.securityapi;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;

@Service
public class CsrPdfService {

    public byte[] generateCsrPdf(CsrEntity csr) throws Exception {

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        Document document = new Document();
        PdfWriter.getInstance(document, outputStream);

        document.open();

        Font title = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);
        Font normal = FontFactory.getFont(FontFactory.HELVETICA, 11);
        Font mono = FontFactory.getFont(FontFactory.COURIER, 9);

        document.add(new Paragraph("Certificate Signing Request (CSR)", title));
        document.add(new Paragraph(" "));
        document.add(new Paragraph("Generated By: " + csr.getUsername(), normal));
        document.add(new Paragraph("Generated On: " + csr.getCreatedAt(), normal));
        document.add(new Paragraph(" "));

        document.add(new Paragraph("CSR Details", title));
        document.add(new Paragraph("Common Name: " + csr.getCommonName(), normal));
        document.add(new Paragraph("Email: " + csr.getEmail(), normal));
        document.add(new Paragraph("Organization: " + csr.getOrganization(), normal));
        document.add(new Paragraph("Organizational Unit: " + csr.getOrganizationalUnit(), normal));
        document.add(new Paragraph("State: " + csr.getState(), normal));
        document.add(new Paragraph("Country: " + csr.getCountry(), normal));
        document.add(new Paragraph("Key Size: RSA " + csr.getRsaKeySize(), normal));
        document.add(new Paragraph("Hash Algorithm: " + csr.getHashAlgorithm(), normal));

        document.add(new Paragraph(" "));
        document.add(new Paragraph("Generated CSR", title));
        document.add(new Paragraph(" "));
        document.add(new Paragraph(csr.getCsrPem(), mono));

        document.close();
        return outputStream.toByteArray();
    }
}
